title: site
template: true

fields:

  logo:
    label: Logo
    type:  image
    width: 1/2

  alert:
    label: Alert Newsletter
    type:  text
  about:
    label: About
    type: text
  about_link:
    label: About Link
    type: page
  shop:
    label: Shop
    type: text
  shop_link:
    label: Shop Link
    type: url
  meta:
    label: Meta
    type: headline
    help: Metadaten sind global, sofern nicht auf Seiten einzeln definiert

  title:
    label: Title
    type:  text

  author:
    label: Meta Author
    type:  text

  description:
    label: Meta Description
    type:  textarea

  keywords:
    label: Meta Keywords
    type:  tags

  copyright:
    label: Copyright
    type:  text

  seo:
    type: seo

  footer:
    label: Footer
    type: headline

  footer_1:
    label: Links
    type: textarea
    width: 1/3

  footer_2:
    label: Mitte
    type: textarea
    width: 1/3

  footer_3:
    label: Rechts
    type: textarea
    width: 1/3
